### PR TITLE
Add the ability to share cookies between requests

### PR DESCRIPTION
**Pull request by bastien-phi**

### CODE REVIEW

**Comment by adamwathan** [comment]
Thinking about the API for this a bit, I think it would be better if we didn't use a global cookie jar and instead `withCookies` took the cookies as a parameter.

So maybe the whole thing would look like:

```
$responseA = Zttp::get('http://foo.example');
$responseB = Zttp::withCookies($responseA->cookies())->get('http://bar.example');
```

Do you think that API is possible? Seems like we should be able to make it work by always using a fresh CookieJar instance for requests that *don't* say `withCookies`, or reuse the CookieJar that's passed in if it is passed in.

**Comment by bastien-phi** [comment]
I will work on it ;-)

**Comment by bastien-phi** [comment]
Hey @adamwathan , what about this PR ?

**Comment by justmd5** [comment]
@adamwathan why not merge this pull？i need this very much！

**Comment by m1guelpf** [comment]
Hey @adamwathan sorry to ping you but is there any chance of this getting merged?

**Comment by adamwathan** [comment]
Merged and tagged.

**Pull request merged**
