### PR TITLE
Add xml method

### PR DESCRIPTION
**Pull request by faustbrian**

### CODE REVIEW

**Comment by jellebreuer** [comment]
+1

**Comment by adamwathan** [comment]
If you can add tests for this happy to merge.

**Comment by sixlive** [comment]
ZttpResponse is now macroable. So this could be accomplished outide of Zttp.

```php
<?php

ZttpResponse::macro('xml', function () {
    return simplexml_load_string(
        utf8_encode($this->response->getBody()),
        'SimpleXMLElement', LIBXML_NOCDATA | LIBXML_NOBLANKS | LIBXML_NOERROR
    );
});

// ...

$response = Zttp::get($this->url('/xml-response'));
$response->xml();
```

Since there are so many different ways of handling XML I think it might be best to leave it as a macro and skip native support.

**Comment by adamwathan** [comment]
Like @sixlive mentioned, for now I think the best way to handle this is to use a macro. I looked into the XML stuff a bit and it seems like there's some gotchas to worry about with error handling and poorly formatted XML responses, and since I don't personally work with XML on the projects where I use Zttp I'm not totally comfortable being on the hook for supporting it.

Thanks for the contribution though, I do appreciate it!

**Pull request closed without merging**
